### ISSUE TITLE
Can't Connect to Discord on Linux

### ISSUE THREAD

**Issue by How-Bout-No** [oonqt/MBCord#10]
**Describe the bug**
MBCord doesn't show anything in Discord when running on Linux, but it worked fine running Windows on the same machine.

**Expected behavior**
For MBCord to show what's playing in Discord.

**Error**
error: Failed to connect to Discord. Attempting to reconnect in 30 seconds

**Desktop (please complete the following information):**
 - OS: Pop OS
 - Server Type: Jellyfin
 - Version 2.1.7

**Comment by oonqt** [comment]
That's strange considering Pop OS is based on Ubuntu which is what I used for all my linux testing..

Give me a couple days until I spin up a Pop!_OS VM and I'll get back to you..

**Comment by How-Bout-No** [comment]
I was able to do some quick testing on my end, it just seems that MBCord doesn't work with the Discord from the Pop Shop nor the Discord from KDE's Discover, only the deb from the official site. However I don't know what would be causing either version to not work with MBCord properly, other than maybe it's because the Pop Shop version seems to be a flatpak, and Discover's is a snap package.

**Comment by oonqt** [comment]
Do any other rich presence applications work with those versions?

**Comment by How-Bout-No** [comment]
I tested a few games that I know have rich presence and they didn't show up. Even manually going into "Game Activity" doesn't show anything relevant on the system. Seems to just be how the Snap and Flatpak distributions work, so I guess there isn't really a fix for that for now.

**Comment by oonqt** [comment]
Thank you, hopefully I'll remember to put this in the FAQ.
