### ISSUE TITLE
Not showing activity

### ISSUE THREAD

**Issue by Rexxezz** [oonqt/MBCord#12]
set it up all correctly as the wiki says but nothing is showing up in my status. I tried with stable and ptb discord but nothing...
I also opened as an administrator but nothing either
I have entered all my data correctly and in the logs says is conected to server but nothing is showing up

Idk what else can i do... Sorry if I have bad english.

**Comment by oonqt** [comment]
Have you been able to get any other rich presence apps to Display?

**Comment by Rexxezz** [comment]
Yes, all of them work perfectly fine.

**Comment by oonqt** [comment]
Are you running on Emby or Jellyfin, and which version of those are you running on? I'll assume you're running on Windows 10 judging by your mention of opening it as an administrator

**Comment by Rexxezz** [comment]
running emby v4.5.2.0 on windows 10

windows 10 version; 2004

**Comment by oonqt** [comment]
Could you try to enable debug logging and try playing some and let it run for a bit? We could find a clue as to what may be going wrong there

Tray Icon -> Log Level -> Debug

**Comment by ImVerum** [comment]
I am experiencing the same issue with Jellyfin 10.6.4. I am running Discord and MBCord on Manjaro. I tried to play videos and music from both the web client and the Infuse iOS app, in both cases it didn't display anything in my status.
Logs: [MBCord-1604697264.txt](https://github.com/oonqt/MBCord/files/5503541/MBCord-1604697264.txt)

**Comment by oonqt** [comment]
`[Fri Nov 06 2020 22:16:40 GMT+0100 (Central European Standard Time)] debug: No session, clearing activity`

This indicates that we successfully made a request to the server, however there we no sessions active and therefore nothing to display as the status. Are you sure that the user that you are signed into on your clients is the same user that you have signed into MBCord? MBCord will only display the status for the user it is signed in as.

**Comment by ImVerum** [comment]
That might have been the cause, I just reconfigured MBCord but this time I used the correct capitalization on my username. I am not sure if that caused the problem, but now it's working fine.

**Comment by oonqt** [comment]
I'm certain that's the cause of it, by the looks of it I'm not changing the username to lowercase when filtering out sessions, so if the casing doesn't match, it won't pick up on the session. I'll fix this in the next version.

**Comment by oonqt** [comment]
If you were having the same issue as ImVerum was, [this new version](https://github.com/oonqt/MBCord/releases/latest) should solve it. Let me know how it goes.

**Comment by oonqt** [comment]
Assuming this is fixed due to no responses, feel free to reopen if you are still experiencing issues.
