### ISSUE TITLE
Support for multiple servers

### ISSUE THREAD

**Issue by TGuerillon** [oonqt/MBCord#13]
**Describe the feature/change you'd like**
It would be great if you could add something to connect two or more media servers to MBcord
**Additional context**
When you have two servers, on running on your home computer and on running on a remote server, I wish I could connect both

**Comment by oonqt** [comment]
I'm surprised I haven't thought about this one before. I'll mess around with multi-server support later this week

**Comment by 6days9weeks** [comment]
Is this still being worked on? The issue is few months old now.

**Comment by oonqt** [comment]
Yes, apologies for the delays. I started working on v3 about 2 weeks ago, however I had to stop as I needed to prepare for & complete all my exams. Right now I'm just finishing up polishing the multi-server switch system. I'll be able to finish up & release once I get back from my trip next thursday.

**Comment by 6days9weeks** [comment]
Thanks for the response ^^. Goodluck with your exams!

**Comment by oonqt** [comment]
Just finishing things up now, one last thing: If a user adds multiple servers, should we automatically attempt to find which server is in use, and set it as their Discord status? One downside with this approach is that if a user has a shared account on one server, it could lead to issues where if another user on the shared account is playing something, it might lead to the incorrect status being displayed if the user is playing something on another server. If we go the other route where the user has to manually select which server to use from a context menu, it's a bit counterintuitive and could be a bit annoying to have to manually switch servers. The current system I have in place right now is a manual selection via context menu in the tray.

**Comment by 6days9weeks** [comment]
I personally would prefer switching via the menu instead of the automatic thing, but it goes down upto you what you want to implement.

**Comment by oonqt** [comment]
Yeah I'll probably leave it to the manual switching for now since it's what I already implemented. I may just add a checkbox toggle in the tray menu to enable experimental automatic server switching so we can get the best of both worlds.
