### ISSUE TITLE
Can't display TV Shows with missing episode number

### ISSUE THREAD

**Issue by ImVerum** [oonqt/MBCord#14]
**Describe the bug**
When I play a TV Show with missing episode number in it's metadata, MBCord doesn't display it in my game activity but logs an error instead.

**Expected behavior**
Currently playing media is displayed in Discord game activity

**Screenshots**
Metadata (Missing Episode number): ![ 6  Nov 2020 22-51 52](https://user-images.githubusercontent.com/26145882/98418199-b2a61c00-2082-11eb-8660-f3e2c5bf3a60.png)

**Error**
[MBCord-1604699214.txt](https://github.com/oonqt/MBCord/files/5503697/MBCord-1604699214.txt)
Line 3622: `[Fri Nov 06 2020 22:47:55 GMT+0100 (Central European Standard Time)] error: Failed to set activity: TypeError: Cannot read property 'toString' of undefined`

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Server Type: Jellyfin
 - Version 10.6.4

**Comment by oonqt** [comment]
I was supposed to do this a while ago, looks like I have forgotten. I'll fix this (and possibly some other) cases for the next release.

**Comment by oonqt** [comment]
Should be good to go in the [latest](https://github.com/oonqt/MBCord/releases/latest) release. Let me know how it goes.

**Comment by ImVerum** [comment]
Seems to be working now, thanks for the quick fix!
