### ISSUE TITLE
Data Usage seems excessive when using MBCord

### ISSUE THREAD

**Issue by fringillidaes** [oonqt/MBCord#16]
** Replace [] with [x] to signify you've completed the following

** [x] I have read over the setup guide (https://github.com/oonqt/MBCord/wiki/Initial-Setup)

** [x] I have read over the commonly asked questions (https://github.com/oonqt/MBCord/wiki/Commonly-Asked-Issues-Questions)

Over the last 30 days this is my data usage with light watching https://i.imgur.com/gzsJUJY.png. It's usually higher when I watch more upwards of 100GB. Is this intentional, or can this be modified in some way?

**Comment by oonqt** [comment]
This is something that I have not seen before. I'm only getting a couple megabytes on my main Windows 10 machine within the past 30 days. I think I might know what's leading to this high data usage, so if you could answer this question it would help narrow it down:

Are you using a shared server, such as one you'd pay monthly for off of r/embyshares that would have a lot of users, or are you using a personal server that you can confirm has a decent amount of users/devices on it?

**Comment by fringillidaes** [comment]
It’s a personal server with maybe 4-5 users with 10 registered devices. Let me know what I can try or give you and can send it your way.

**Comment by oonqt** [comment]
Would you be able to enable debug logging and let the program run like normal for a few days, and then upload the logs? You might need to compress them up since they'll likely grow extremely large if this much data is being used.

**Comment by fringillidaes** [comment]
Yes will do.

**Comment by fringillidaes** [comment]
Closing as I am not seeing this issue anymore. :)
