### ISSUE TITLE
Time elapsed option

### ISSUE THREAD

**Issue by ephibu** [oonqt/MBCord#18]
It would be nice if we could get an option of displaying the time elapsed when watching a video on Jellyfin.

**Comment by oonqt** [comment]
I will implement a toggle somewhere to switch between elapse and remaining time soon ™️

**Comment by ephibu** [comment]
Sounds good!

**Comment by oonqt** [comment]
Completed (sorry for 5 month wait)

This can be accessed via the tray in [latest version](https://github.com/oonqt/MBCord/latest)
