### ISSUE TITLE
It would be nice if you could run this on my nas rather than my pc

### ISSUE THREAD

**Issue by xrishox** [oonqt/MBCord#2]
Is there some sort of requirement that discord and this are running on the same box? Is there any reason it couldn't be an external service running on my nas?

**Comment by oonqt** [comment]
Technically you could, but only if you have Discord running on the NAS. EmbyCord relies on communicating to discord over IPC (interprocess communication), so it has to be running on the same machine as Discord is. If you could run the Discord desktop client in the background with EmbyCord on the NAS, it would work fine.
