### ISSUE TITLE
MBCord no longer working

### ISSUE THREAD

**Issue by mattssn11** [oonqt/MBCord#21]
**Describe the bug**
MBCord started randomly not working anymore, it will connect to my server but gives an error it cannot connect to Discord. 

**Expected behavior**
Rich presence to work when watching something in Jellyfin

**Screenshots**

**Error**
[MBCord-1614454474.txt](https://github.com/oonqt/MBCord/files/6055259/MBCord-1614454474.txt)
[Sat Feb 27 2021 12:42:24 GMT-0700 (Mountain Standard Time)] info: Connected to Discord
[Sat Feb 27 2021 12:42:24 GMT-0700 (Mountain Standard Time)] info: Connected to Discord
[Sat Feb 27 2021 12:42:28 GMT-0700 (Mountain Standard Time)] info: Connected to Discord
[Sat Feb 27 2021 12:42:28 GMT-0700 (Mountain Standard Time)] info: Connected to Discord
[Sat Feb 27 2021 12:42:34 GMT-0700 (Mountain Standard Time)] info: Connected to Discord
[Sat Feb 27 2021 12:42:34 GMT-0700 (Mountain Standard Time)] warn: Discord RPC connection closed. Attempting to reconnect in 30 seconds
[Sat Feb 27 2021 12:42:34 GMT-0700 (Mountain Standard Time)] error: Failed to connect to Discord. Attempting to reconnect in 30 seconds
[Sat Feb 27 2021 12:42:34 GMT-0700 (Mountain Standard Time)] info: Connected to Discord
[Sat Feb 27 2021 12:42:34 GMT-0700 (Mountain Standard Time)] error: Failed to connect to Discord. Attempting to reconnect in 30 seconds
[Sat Feb 27 2021 12:42:34 GMT-0700 (Mountain Standard Time)] error: Failed to connect to Discord. Attempting to reconnect in 30 seconds

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Server Type: Jellyfin
 - Version 10.6.4

**Additional context**
I have reinstalled discord and reset MBCord, also cleared Appdata for MBCord, but issue still occurs, could this be a change to Discord on an update?

**Comment by oonqt** [comment]
The Discord account that the rich presence client IDs were on got deleted, so those client IDs were made inaccessible. I've released a new version that includes valid client IDs which has fixed the issue.

**Comment by mattssn11** [comment]
Just got the push, will check now!

**Comment by mattssn11** [comment]
Working now, Thanks, will close!
