### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by LeviSnoot** [oonqt/MBCord#23]
**Describe the bug**
MBCord appears to connect to Discord, and I am able to sign in to my Jellyfin server, but everything past that does not work. It does not display RPC on Discord, and if I try to open the option "Set Ignored Libraries", it will either show the error "Failed to fetch libraries for your user. Please try the reload button." or if I untick "Display Status" it will not show an error message but the window will load indefinitely with no results.

**Expected behavior**
Discord RPC working and the ability to configure my libraries.

**Screenshots**
[Screenshot 1](https://i.levi.land/7CloQ)
[Screenshot 2](https://i.levi.land/uyQ2m)

**Error**
```
[Sun May 09 2021 13:41:00 GMT+0200 (Central European Summer Time)] info: Connected to Discord
[Sun May 09 2021 13:41:02 GMT+0200 (Central European Summer Time)] error: Failed to set activity: Status: 500 Response: "Error processing request."
[Sun May 09 2021 13:41:33 GMT+0200 (Central European Summer Time)] error: Interal ID fetch failure: Failed to get library ID: Status: 500 Response: "Error processing request." at library Movies
[Sun May 09 2021 13:41:33 GMT+0200 (Central European Summer Time)] error: Failed to set activity: Status: 500 Response: "Error processing request."
[Sun May 09 2021 13:41:36 GMT+0200 (Central European Summer Time)] error: Interal ID fetch failure: Failed to get library ID: Status: 500 Response: "Error processing request." at library Movies
[Sun May 09 2021 13:41:48 GMT+0200 (Central European Summer Time)] error: Failed to set activity: Status: 500 Response: "Error processing request."
[Sun May 09 2021 13:42:03 GMT+0200 (Central European Summer Time)] error: Failed to set activity: Status: 500 Response: "Error processing request."
[Sun May 09 2021 13:42:18 GMT+0200 (Central European Summer Time)] error: Failed to set activity: Status: 500 Response: "Error processing request."
[Sun May 09 2021 13:42:33 GMT+0200 (Central European Summer Time)] error: Failed to set activity: Status: 500 Response: "Error processing request."
[Sun May 09 2021 13:42:48 GMT+0200 (Central European Summer Time)] error: Failed to set activity: Status: 500 Response: "Error processing request."
[Sun May 09 2021 13:43:03 GMT+0200 (Central European Summer Time)] error: Failed to set activity: Status: 500 Response: "Error processing request."
[Sun May 09 2021 13:43:18 GMT+0200 (Central European Summer Time)] error: Failed to set activity: Status: 500 Response: "Error processing request."
[Sun May 09 2021 13:43:33 GMT+0200 (Central European Summer Time)] error: Failed to set activity: Status: 500 Response: "Error processing request."
[Sun May 09 2021 13:44:08 GMT+0200 (Central European Summer Time)] error: Interal ID fetch failure: Failed to get library ID: Status: 500 Response: "Error processing request." at library Movies
[Sun May 09 2021 13:44:08 GMT+0200 (Central European Summer Time)] error: Failed to set activity: Status: 500 Response: "Error processing request."
[Sun May 09 2021 13:45:00 GMT+0200 (Central European Summer Time)] error: Interal ID fetch failure: Failed to get library ID: Status: 500 Response: "Error processing request." at library Movies
[Sun May 09 2021 13:45:00 GMT+0200 (Central European Summer Time)] error: Failed to set activity: Status: 500 Response: "Error processing request."
[Sun May 09 2021 13:45:06 GMT+0200 (Central European Summer Time)] debug: doDisplayStatus disabled
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Version 20H2
 - Server Type: Jellyfin
 - Version 10.7.5

**Comment by oonqt** [comment]
Hello, are you able to recreate this issue using the Jellyfin demo server @ https://demo.jellydin.org/stable?

**Comment by LeviSnoot** [comment]
> Hello, are you able to recreate this issue using the Jellyfin demo server @ https://demo.jellydin.org/stable?

Unfortunately I am [unable to sign in](https://i.levi.land/F1wgY) to that server directly using MBCord.

I instead tried signing into my own server and then editing the config.json to point to the Demo jellyfin which appears to have worked, however the exact same behavior happens as with my own server.

**Comment by oonqt** [comment]
Sorry, forgot to leave an update because I was tired, but I spun up a Jellyfin 10.7.5 instance on my Server and  wasn't able to reproduce it immediately. I'm going to try and do some more testing this weekend to see if I can reproduce it myself.

**Comment by LeviSnoot** [comment]
> Sorry, forgot to leave an update because I was tired, but I spun up a Jellyfin 10.7.5 instance on my Server and wasn't able to reproduce it immediately. I'm going to try and do some more testing this weekend to see if I can reproduce it myself.

My apartment's being renovated right now so I'm on a different network, unable to reproduce the issue for myself. I feel pretty confident now that it's caused by the reverse proxy (Caddy) as MBCord connects to the local IP address with no issues on this network.

**Comment by oonqt** [comment]
It still doesn't make sense why Jellyfin was returning a 500 response on the Ancestors endpoint, I'm wondering if something got screwed up with the library DB after the upgrade and fixed itself after a library scan. Let me know if it happens when you're able to connect through Caddy again, that would be very interesting.
