### ISSUE TITLE
Very high CPU and RAM usage

### ISSUE THREAD

**Issue by 123321mario** [oonqt/MBCord#25]
**Describe the bug**
The app randomly stops working and start using a lot of ressources for no reason making other electron app crash in loop

**Expected behavior**
i was just expecting it to work normally

**Screenshots**
![image](https://user-images.githubusercontent.com/33780173/121869394-4a977280-cd02-11eb-8a01-f25071f6227e.png)

**Error**
well the log files are a bit gigantic
![image](https://user-images.githubusercontent.com/33780173/121869670-934f2b80-cd02-11eb-9bd2-4ff19df17e57.png)
but 99.9% of the lines says `error: Failed to connect to Discord. Attempting to reconnect in 30 seconds` , `info: Connected to Discord` or `warn: Discord RPC connection closed. Attempting to reconnect in 30 seconds`

**Desktop:**
 - OS: Windows 10 21H1
 - Server Type: Emby 4.6.2.0
 - Version 2.3.13 (i had the bug before)

**Comment by oonqt** [comment]
I think what is going on here is every time the connection fails, it gets stuck in a loop and keeps calling the rpc connect function over and over until the program eventually crashes or system runs out of memory. I'm reworking this reconnect system in V3 which should be coming out in a couple of weeks as I'm on vacation and have a couple of things I need to add.

**Comment by zmeizy** [comment]
Jellyfin.exe is also having high CPU usage when MBCord uses a lot of resources. When MBCord gets closed, the CPU usage from Jellyfin.exe drops dramatically.
