### ISSUE TITLE
Support for multi Accounts on one Server

### ISSUE THREAD

**Issue by MohandL3G** [oonqt/MBCord#26]
If one Server have multiple accounts and if two accounts watching different accounts using different Devices, everyone will have it's own Discord Stats on they're accounts.

Sorry for bad English.
And thanks for everything.

**Comment by oonqt** [comment]
I'm not exactly sure what you're asking for here, could you elaborate a bit more on what you're looking for?

**Comment by MohandL3G** [comment]
Don't worry I found out how to do this.

Sorry for asking without even trying.
