### ISSUE TITLE
MBCord randomly exiting

### ISSUE THREAD

**Issue by realtofuine** [oonqt/MBCord#39]
**Describe the bug**
A clear and concise description of what the bug is. Explain the steps that you took leading up to the bug to help aid in recreating it.

Sometimes when I am watching or listening to something on Jellyfin and MBCord is running, MBCord exits without notice and Jellyfin no longer appears in Discord status.

**Expected behavior**

MBCord should stay running in the background unless manually exited by the user.

**Screenshots**

**Error**
* Attach the most recent log. Logs can be found by right clicking the tray application and clicking "Show Logs". Although it does its best to remove any, it's a good idea to give the logs a quick scrub to ensure there aren't any credentials/addresses*

The log doesn't really show anything but if you want:
[Sat Apr 23 2022 13:25:52 GMT-0500 (Central Daylight Time)] info: Connected to Discord

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Server Type: Jellyfin
 - Version MBCord 2.3.13, Jellyfin 10.7.7

**Additional context**

**Comment by realtofuine** [comment]
If anyone is looking for kind of an immediate "fix", just use this: [Restart on Crash](https://www.majorgeeks.com/content/page/restart_on_crash_auto_restarts_crashed_apps.html)
program and set it to monitor MBCord.exe.

**Comment by realtofuine** [comment]
@oonqt i mean my fix isnt really a fix. it keeps crashing still to this day and sometimes it crashes like 100 times in a row every 30 seconds lol

**Comment by oonqt** [comment]
You need the blockchain 🤓

**Comment by realtofuine** [comment]
what? lol

**Comment by oonqt** [comment]
You gotta inject the blockchain into the code. It can be accomplished by doing MBCord.App.Blockchain.inject(0x69). Thanks for reading have a great night.

**Comment by realtofuine** [comment]
thanks for the quick solution lol

i will find the inject blockchain

(but wait i still cant understand if this is a joke or not)
