### ISSUE TITLE
Change emby name and image

### ISSUE THREAD

**Issue by Makassu** [oonqt/MBCord#45]
** Replace [] with [x] to signify you've completed the following

** [x] I have read over the setup guide (https://github.com/oonqt/MBCord/wiki/Initial-Setup)

** [x] I have read over the commonly asked questions (https://github.com/oonqt/MBCord/wiki/Commonly-Asked-Issues-Questions)

is there any way to change the emby name and image in rich presence?

another question: is there any way to leave MBCord already configured? to come with pre selected server?
just enter username and password?

**Comment by Makassu** [comment]
I'm talking about a still image*

**Comment by oonqt** [comment]
this feature has been added please downlaod the latest version

**Comment by Makassu** [comment]
I have the latest version, and I can't see any options.
