### ISSUE TITLE
Crashes on startup ~ PopOS (Linux) 22.04LTS

### ISSUE THREAD

**Issue by nickheyer** [oonqt/MBCord#46]
**Describe the bug**
Assuming the entry method for this app is "MBCord". It isn't running. Crashes on startup. See error below.

**Error**
"[584059:1003/211048.701029:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)"

**Desktop (please complete the following information):**
 - OS: PopOS 22.04LTS
 - Server Type: Emby

**Comment by disconsolated** [comment]
Same issue here. Would love a fix for this.

**Comment by oonqt** [comment]
fixed redownloas latest versiom thanks
