### ISSUE TITLE
Doesn't show anything on Discord

### ISSUE THREAD

**Issue by MohandL3G** [oonqt/MBCord#5]
**Describe the bug**
I don't know why it doesn't work, it doesn't show anything on Discord when playing directly from Browser or from Kodi.

**Expected behavior**
it should show what is being Watching.

Screenshots:
![Annotation 2020-04-02 103307](https://user-images.githubusercontent.com/31743237/78227675-e954fc00-74cd-11ea-856b-42a319b0bb58.jpg)

Error:
[EmbyCord-1585815861.txt](https://github.com/oonqt/MBCord/files/4419716/EmbyCord-1585815861.txt)

Versions:
 - OS: Winodws 10 (1909)
 - Version [1.1.0]

**Comment by oonqt** [comment]
I haven't done too much research into it, but I just got an idea today of what might have happened (my old Discord got deleted along with the jellyfin/emby client IDs). I'll try to release a fix for it soon, so check back in a day or two.

**Comment by oonqt** [comment]
Fixed, see: https://github.com/oonqt/MBCord/releases/tag/1.1.2

Let me know if it works so I can close this issue, thanks!

More updates coming soon

**Comment by MohandL3G** [comment]
Thanks it works now 😊
