### ISSUE TITLE
Can't connect to Discord

### ISSUE THREAD

**Issue by JonathanTF2** [oonqt/MBCord#6]
**Describe the bug**

The application can't connect to Discord again.

**Error**
Attached.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 1.0.9]

Windows 1.1.2

**Additional context**

I built the program using another Discord application ID and it works. Would it be possible to get the images that you used on it?

**Comment by oonqt** [comment]
That's strange that that is happening. Haven't seen this before

Anyways, here are the icons (go under assets in the rich presence tab of your app on the dev panel):

https://cdn.discordapp.com/app-assets/696111620220256383/696142404746739722.png?size=512 (name: pause)
https://cdn.discordapp.com/app-assets/696111620220256383/696142404884889650.png?size=512 (name: play)
https://cdn.discordapp.com/app-assets/696111620220256383/696115822317535273.png?size=512 (name: large)
