### ISSUE TITLE
Feature: Display Album Image in Discord

### ISSUE THREAD

**Issue by mlunax** [oonqt/MBCord#7]
Not so much important but nice to see feature: Display an album's image in Discord Embeded.

**Comment by Zusier** [comment]
I was gonna write a suggestion basically about this too! +1

**Comment by oonqt** [comment]
If this was possible, I can assure you I most definitely would have implemented it. Unfortunately, Discord RPC only allows you to have static images defined, you cannot dynamically change the images. I guess technically I could hack together a solution, but it's more work for both me and the end user to get it working.

**Comment by cikeZ00** [comment]
Might be worth mentioning that it should be possible to implement this without the end user doing much work.

Prime example of this being fetchcord.
[https://github.com/MrPotatoBobx/FetchCord#examples](url)
