### ISSUE TITLE
Bug: If a song was skipped the application doesn't change it to actually played.

### ISSUE THREAD

**Issue by mlunax** [oonqt/MBCord#8]
**Describe the bug**
If a song was skipped the application doesn't change it to actually played.
After the timer "xx:xx left" the timer stops and songs don't change.

**Expected behavior**
Update the song in Discord embedded.

**Error**
Nothing when the song is skipped.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Server Type: Jellyfin
 - Version 10.6.0 

**Additional context**
To "fix" problem Discord is required to restart (e.g. ctrl+r) and uncheck and check "Display as status".
A restart of MBCord works too.

**Comment by oonqt** [comment]
This might be a thing with Discord, Discord statuses will freeze sometimes, but regardless I'll take a look in a couple hours. I'm just about to release V2, so if this is an issue with MBCord, hopefully it'll be resolved

**Comment by oonqt** [comment]
Assuming fixed/resolved due to no response in several months, feel free to reopen if not resolved.
