### ISSUE TITLE
Add the ability to disable Startup Pop-up Screen

### ISSUE THREAD

**Issue by Miko36110** [oonqt/MBCord#9]
**Describe the feature/change you'd like**
I would love an option to disable the "MBCord has been minimized to the tray" pop-up.
It gets annoying every time I start up my PC.

This pop up screen ↓
![MBCord_fqKTLo9ElG](https://user-images.githubusercontent.com/52654251/84247483-23ccbc00-ab43-11ea-9db5-dcdaf8f40ccc.png)

**Comment by oonqt** [comment]
I agree, I was actually just thinking about doing this earlier today

There isn't any reason for the dialog box to show up whenever the computer starts, it should only be shown when the app is manually started to avoid the inevitable confusion of "where did app go????"


###### _A start on the repository is appreciated :)_

**Comment by oonqt** [comment]
After concideration, I decided the best option would be to just use the OS's

**Comment by oonqt** [comment]
I have switched this dialog window out in favor of the OS's native notification system. This will be a lot less intrusive now:

[example](https://i.memester.xyz/u/6vr.png)

Marking as completed and closing, will be included in the next release
